= Oslonøkkelen adapter

One of the main design goals behind Oslonøkkelen is that it should support all kinds of third party systems. To that end
we provide something we call our adapter api. The goal of these adapters are to work as bridges and translate between
Oslonøkkelen and existing systems without modifications to either system.

== Target audience

The target audience for this document is developers who want to add support for new such systems using our adapter api.
Our adapter api works as a bridge between Oslonøkkelen backend and what ever third party api / system you want. Some
examples of what this api has been used for so far:

- Opening doors controlled by system x, y or z
- Authenticating Deichman library users
- Dropping beer from cotton clouds
- Lowering gingerbread castle drawbridge
- Fetching QR / bar codes


=== Overview

This is a high level view. The goal is to allow others to publish locks / doors in Oslonøkkelen using a generic api.
Oslonøkkelen will periodically poll your adapter for what we call a manifest. The manifest is a description of what
your adapter can do. The manifest will contain a list of _things_ and _actions_ that can be performed on those things.
This is described in more detail further down. These actions can be mapped to operations available to users of
Oslonøkkelen and when a user decides to trigger one of these operations our backend will send a request to your adapter
that in turn will talk to your system to perform it.



[svgbob,adapter-new-design,svg]
....
               .~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
               :                                 :
     Internet  :                Adapter API      : Internet                      Any protocol
               :                         \       :                             / you need
               :                         |       :                             |
               :                         v       :                             |
.-----. https  :  +-----+--------------+-----+   : https   +--------------+    v    +-----+-------------+
| App |--------:->| API | Oslonøkkelen | API |<--:-------->| Your adapter |<------->| API | Your system |
'-----'        :  +-----+--------------+-----+   :         +--------------+         +-----+-------------+
               :                                 :                 ^
               :                                 :                 |
               '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'                  \ Implemented using the
                                                                      language you prefer
....

=== Manifests

The manifest is loosely inspired by Mozillas https://www.w3.org/TR/wot-thing-description/[WoT RFC], although the RFC has evolved a bit since.
The important thing is that each adapter can expose a number of actions and those actions can be mapped to operations users of Oslonøkkelen can execute from the app.

==== Example
....
things:
  - id: front-door
    description: The front door
    actions:
      - id: open
        description: Opens the front door (door pump)
      - id: unlock
        description: Unlocks the bolt
        requiredParameters:
          - fodselsnummer
  - id: outdoor-lights
    description: 5 outdoor lamps
    actions:
      - id: turn-off
      - id: dim-30-percent
      - id: dim-50-percent
....

This manifest tells Oslonøkkelen what the adapter can do. An administrator in Oslonøkkelen can map these actions to operations in the
app. We support chaining multiple actions to allow one action to work as authorization for another and to support scenarios
like unlocking a door and turning on the lights with a single operation in Oslonøkkelen.

== Authentication

The mechanism we use for authentication is similar to the one used in openid connect.

All requests from Oslonøkkelen to your adapter will be signed https://auth0.com/docs/tokens/json-web-tokens[JWTs] and
your adapter is responsible for downloading (and cache) the public keys from Oslonøkkelen and verify the signature of
these tokens. Each request contains the id of the key used for signing (KID) and this id can be used to cache public keys
to avoid looking up the same key multiple times.


== Protocol


=== Polling manifests

After the new adapter has been registered in our configuration, backend will start polling its manifest every n minutes.
This also doubles as monitoring / alerting in case a third party system starts misbehaving or goes offline.
It is important that the third party system has a proper TLS certificate and that we verify it.

[seqdiag,adapter-manifest-poll,svg]
....
seqdiag {
  backend; config-db; third-party-adapter;

  backend => third-party-adapter [ label = "GET .../manifest", return = "Manifest", note = "This will be repeated\nevery n minutes" ] {
    backend => config-db [ label = "Manifest update" ]
  }
}
....


=== Executing a request

This is the fun part!
The user has pressed a button in the app and expects a door to open.
When the user hits the big open button the app will make a request to backend that runs authorization, figures out what adapters are involved with the request and forwards the request to the endpoint registered in the process described above.

All this is might be easier to visualize with a sequence diagram:

[seqdiag,adapter-execute,svg]
....
seqdiag {
  app; backend; auth; third-party-adapter;

  app => backend [ label = "Open door A", return = "OK", note = "Device is signed\nwith device key" ] {
    backend => auth [ label = "Verify device key", return = "OK" ]
    backend => third-party-adapter [ label = "execute: action-door-a", return = "ack", note = "Request is signed\nwith kid=backend-key-123" ] {
      third-party-adapter => backend [ label = "Fetch key: backend-key-123", return = "JWK\n(json web key)", note = "Will only have to fetch key\nif not already in cache.\nThis is to verify that the request\nactually is sent by Oslonøkkelen." ]
      third-party-adapter -> third-party-adapter [ label = "Verify signature" ]
      third-party-adapter -> third-party-adapter [ label = "Open door" ]
    }
  }

}
....

The important part here is that the adapter is responsible for downloading the correct key (the signed token contains a key id)
from Oslonøkkelen backend and verify that the token actually is signed by a private key belonging to the public key it downloaded.
Another assumption here is that the adapter verifies Oslonøkkelens TLS certificate.


== Protobuf definition

[%collapsible]
====
[source,protobuf]
----
include::../../../../adapter-protobuf-java/src/main/proto/adapter.proto[]
----
====