= Oslonøkkelen adapter

One of the main design goals behind Oslonøkkelen is that it should support all kinds of third party systems. To that end
we provide something we call our adapter api. The goal of these adapters are to work as bridges and translate between
Oslonøkkelen and existing systems without modifications to either system.

[svgbob,adapter-new-design,svg]
....

                                    oslonøkkelen : adapter                      _ Any protocol
                                                 :                             /  you need
                                                 :                             |
  +-----+ https   +-----+--------------+-----+   : https   +--------------+    v    +-----+-------------+
  | App |-------->| API | Oslonøkkelen | API |---:-------->| Your adapter |<------->| API | Your system |
  +-----+         +-----+--------------+-----+   :         +-------+------+         +-----+-------------+
                                                 :                 ^
                                                 :                 |
                                                 :                  \ Implemented using the
                                                                      language you prefer.
                                                                      Think of it as a bridge
                                                                      between oslonøkkelen and
                                                                      some other system.
....


== Target audience

The target audience for this documentation is developers who want to add support for new such systems using our adapter api.
Our adapter api works as a bridge between Oslonøkkelen backend and what ever third party api / system you want. Some
examples of what this api has been used for so far:

- Opening doors controlled by system x, y or z
- Authenticating Deichman library users
- Dropping beer from cotton clouds
- Lowering gingerbread castle drawbridge
- Fetching QR / bar codes


== Documentation

The list below is order by recommended reading order.

* link:overview.adoc[Overview] - High level view of how an adapter works
* link:protocol.adoc[Protocol] - How Oslonøkkelen and your adapter will communicate
* link:authentication.adoc[Authentication] - How your adapter verifies request
* link:protobuf.adoc[Protobuf] - Message definitions
* link:implementation-checklist.adoc[Implementation checklist] - Things to keep in mind when implementing an adapter